version: 2
jobs:
  build_develop:
      docker:
        - image: circleci/node:7.10-browsers
        - image: circleci/node:7.10-browsers
      
      environment:
          CHROME_BIN: "/usr/bin/google-chrome"
      steps:
         - checkout
         - run: npm install
         - run: npm test 
 
  
