version: 2

jobs:
  build:
    branches:
      only:
        - develop
    docker:
      - image: docker:18.06.1-ce-git
    working_directory: ~/cognitensor_0.1
    parallelism: 1
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: false
          version: 19.03.13
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=10.0.1-r0 \
              bash \
              jq \
              curl \
              nodejs \
              npm
            pip install \
              docker-compose==1.22.0 \
              awscli==1.16.2
      - run:
          name: Build Docker images
          command: docker-compose -f docker-compose-review.yml build
  
